//260 / 12 + 54 % 3 – 85 % 7
//ANALISIS DEL PROBLEMA
//ENTRADA:operacio
//PROCESO:  operacio=260 / 12 + 54 % 3 - 85 % 7
//SALIDA:Escribir(operacio)
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

const read = require('prompt-sync')();
function ejercicio4 (){
   let operacio
   operacio=260 / 12 + 54 % 3 - 85 % 7

   console.log(operacio)
    
}
ejercicio4()