// (5 + 3 * 2) + 9 > 3 * 5 * 14 % 3
//ANALISIS DEL PROBLEMA
//ENTRADA:operac(leer)
//PROCESO:operac=(5 + 3 * 2) + 9 > 3 * 5 * 14 % 3 
//SALIDA:operac
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

const read = require('prompt-sync')();
function ejercicio2 (){
   let operac
   operac=(5 + 3 * 2) + 9 > 3 * 5 * 14 % 3

   console.log(operac)
    
}
ejercicio2()
