// 2 *(4 – 10 + 8)/2* 36 *(1/2)
//ANALISIS DEL PROBLEMA
//ENTRADA:operaci
//PROCESO:
//operaci=2 *(4 - 10 + 8)/2* 36 *(1/2)
//SALIDA:
//console.log(operaci)
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

const read = require('prompt-sync')();
function ejercicio3 (){
   let operaci
   operaci=2 *(4 - 10 + 8)/2* 36 *(1/2)

   console.log(operaci)
    
}
ejercicio3()