//((8 > 2) | | (932 < 23) ) && 4 == 2
//ANALISIS DEL PROBLEMA
//ENTRADA: operacion1
//PROCESO:  operacion1=((8 > 2) || (932 < 23) ) && 4 == 2
//SALIDA:operacion1
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

const read = require('prompt-sync')();
function ejercicio5 (){
   let operacion1
   operacion1=((8 > 2) || (932 < 23) ) && 4 == 2

   console.log(operacion1)
    
}
ejercicio5()